### ISSUE TITLE
女孩特质报错

### ISSUE THREAD

**Issue by sss614** [XyMinxin/Brothel-King-Chinese-Translate#11]
**描述错误**

特质报错

**重现方法**
重现行为的步骤：
使用了较新的女孩包后，每次进游戏以及每周结束市场更新时就会提示特质错误。

**预期行为**
对您期望发生的事情的清晰而简洁的描述。

**屏幕截图**

![QQ图片20230327231528](https://user-images.githubusercontent.com/90863003/227984782-38843e36-a031-44a5-a591-b92be88c9469.png)
![QQ图片20230327231547](https://user-images.githubusercontent.com/90863003/227984806-d5ab6210-1816-4b36-8466-5d244c6e94e1.png)

**其他描述**
在此处添加有关问题的任何其他描述。

**Comment by XyMinxin** [comment]
我看了一下7月11号的补丁，这个Skilled tounge估计是打错了，文件里是Skilled tongue，建议自己把人物包的配置文件修改一下

我还在合并7月11号的补丁，里面东西有点多，我可以更新一下大概能解决，也可能会出新bug，建议备份好存档和游戏
