### ISSUE TITLE
0.3 Test 无法兼容汉化

### ISSUE THREAD

**Issue by Fiorentsky** [XyMinxin/Brothel-King-Chinese-Translate#22]
### 描述你的问题

尝试将0.2的汉化补丁放入最新的0.3版游戏，发现完全无法运行
一开始是girlclass.rpy报错说存在重复名字为%s的人物
删除汉化包的此文件再覆盖则报错：
File "game/script.rpy", line 229: invalid syntax
        except IOError as (errno, strerror):
看来应该是0.3有较多的新改动，造成原版汉化包的不兼容
不知道作者有没有兴趣做个兼容呢？新内容先不翻译也没关系的

**Comment by XyMinxin** [comment]
看了一下论坛那边，现在还只是0.3的早期版本，下个补丁也估计没过多久会发，并且看样子正式版应该还得等一年左右
0.2的正式版2022-02-11的，后面补丁修复到2022-07-11才更新完
所以现在暂时还不想动，或者要是时间比较多的话，可以加入一起汉化
可以简单教你我之前是怎么汉化的，还有用的啥软件
你可以来做个简单的小适配，然后pr过来

**Comment by Fiorentsky** [comment]
嗯我也翻了一下论坛，我觉得您的想法很有道理，等正式版出了再弄比较好
这个版本本身也还有一些Bug，回滚的时候挺烦的，我先啃啃生肉也没什么问题
我其实也挺感兴趣的，不过我对代码几乎一窍不通，英文倒是还可以
如果正式版发布之后有时间，我很乐意帮忙一起汉化
谢谢您的汉化工作和回复

**Comment by Silent-Crow** [comment]
现在GPT3.5  4.0都挺好使的了吧，主要还是专业用语翻译不到位，就没那味了

**Comment by XyMinxin** [comment]
> 现在GPT3.5  4.0都挺好使的了吧，主要还是专业用语翻译不到位，就没那味了

gpt3.5也就那样，错翻一堆，之前反应对话内容到时候后半进度加快了就是用gpt翻的
4.0我这边没有，得花钱买，没钱
要是有好心人愿意提供gpt4.0翻译的话，那这边之后要做0.3版本也好做一点
温馨提醒一下，他这个文本量挺多的，可能会耗费特别多流量，也不知道对话那边有没有新更新的，剧情那边肯定需要翻译的了，第三章的那个剧情
