### ISSUE TITLE
找不到对应的地点

### ISSUE THREAD

**Issue by chaosnihility** [XyMinxin/Brothel-King-Chinese-Translate#23]
### 在提问之前...

- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的汉化
- [ ] 没有修改过游戏内的文件
- [ ] 没有使用旧版存档

### 描述你的问题

找不到对应的地点，第二章有个忍者需要到温泉去等待她，但是找不到温泉，青楼的温泉也没有对应按钮进入。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![2](https://github.com/XyMinxin/Brothel-King-Chinese-Translate/assets/154837814/6cba8ba0-c325-428b-a959-e60a91229798)
![1](https://github.com/XyMinxin/Brothel-King-Chinese-Translate/assets/154837814/7c3ee6d4-9c77-48d7-a1b0-3b443aa55f92)

**Comment by XyMinxin** [comment]
```
    $ game.set_task("去泡温泉，等待铃女的到来。")
    $ daily_events.append(StoryEvent(label = "c2_suzume_onsen", chapter=2, room="onsen", date=calendar.time + 3))

    return


label c2_suzume_onsen(): # Happens at night when the player has an onsen and at least 3 days have passed

    "As the daylight dims and the red lanterns are lit, you stroll around [brothel.name], making sure everything is going well."

    you "Ah, seems like another peaceful night... Wait, what's that noise?"
```

Happens at night when the player has an onsen and at least 3 days have passed
发生在玩家有温泉并且至少过去3天的晚上

你试试看过几天
