### ISSUE TITLE
0.3版本机翻问题

### ISSUE THREAD

**Issue by Silent-Crow** [XyMinxin/Brothel-King-Chinese-Translate#25]
### 描述你的问题

大佬您好，0.3测试版已出，我们有三个人在做机翻和润色，但是用工具扫文本有很多格式对不上，会漏翻。请问你是用的什么工具完成的机翻？如果用空的话，你愿意参与0.3的汉化吗，给我们些技术指导。

**Comment by Silent-Crow** [comment]
提供一下正则就可以了，主要是漏扫。正则加多了又会有大量重复。

**Comment by hu345235901** [comment]
请问我可以参与您的项目吗？
我希望能积攒相关经验，以便日后能完成《jack-o-nine-tails》的汉化项目

**Comment by Silent-Crow** [comment]
> 请问我可以参与您的项目吗？ 我希望能积攒相关经验，以便日后能完成《jack-o-nine-tails》的汉化项目

可以，给个微信或者QQ联系方式

**Comment by hu345235901** [comment]
我的QQ是  345235901

**Comment by Silent-Crow** [comment]
已申请QQ好友

**Comment by XyMinxin** [comment]
如果你说的是对话文本剧情文本那些，那部分我那会纯人力丢给AI翻，每天五十一百行的翻

**Comment by XyMinxin** [comment]
要不发我一份游戏我瞅瞅，之前好像下到过一个0.3的汉化，不知道是不是你们的，玩一会就报错

**Comment by Silent-Crow** [comment]
> 要不发我一份游戏我瞅瞅，之前好像下到过一个0.3的汉化，不知道是不是你们的，玩一会就报错

是我们做的，汉化一直在持续进行，目前倒是不报错了，但人力有限，现在正在修改源代码适配汉化以及润色机翻问题，改着改着就可能报错重来。给个VX拉你进群，正好也有很多想请教大佬的。

**Comment by XyMinxin** [comment]
XYMinxin

**Comment by MiWuZhanShen** [comment]
> 请问我可以参与您的项目吗？ 我希望能积攒相关经验，以便日后能完成《jack-o-nine-tails》的汉化项目

哈哈，jackhf全手动一个一个翻，纯文本，没啥东西，照着以前的翻译就行了，最新的应该就是我上次翻的，制作组更新太勤，我跟不上了，我那个去除疤痕那有BUG，汉化的时候懒了直接复制的，这个没难度，基本全是需要手动精翻，就是出力，一个人没给我累死
