### ISSUE TITLE
图示显示错误

### ISSUE THREAD

**Issue by Jenttt** [XyMinxin/Brothel-King-Chinese-Translate#49]
### 在提问之前...

- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的汉化
- [X] 没有修改过游戏内的文件
- [X] 没有使用旧版存档

### 描述你的问题

性技训练图示变成口

### 如何复现

1. 前往 '女孩卧室'
2. 点击 '任意训练过性技的女孩'
3. 滑动到 '互动'->'训练'
4. 出现问题
![image](https://github.com/XyMinxin/Brothel-King-Chinese-Translate/assets/49702995/ec743af1-dc66-40ea-ac51-c18d7a072383)

### 预期行为

正常显示

### 截图

![image](https://github.com/XyMinxin/Brothel-King-Chinese-Translate/assets/49702995/d8b002d8-a636-4194-8fb7-983dcd142461)

**Comment by Jenttt** [comment]
我试了一下用了230923的汉化补丁不会有这个情况，但是用新补丁覆盖以后就出现这个情况

**Comment by XyMinxin** [comment]
已修复
