### ISSUE TITLE
代码设置错误？

### ISSUE THREAD

**Issue by pig339** [XyMinxin/Brothel-King-Chinese-Translate#53]
### 在提问之前...

- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的汉化
- [X] 没有修改过游戏内的文件
- [ ] 没有使用旧版存档

### 描述你的问题

第一次在瞭望塔那总督贩卖的道具给出的汉化文本是“给予”和“给予与装备”，但这个问题我觉得是老存档的缘故，问题在于无论是“给予”还是“给予与装备”的按钮都无法点击下去，甚至连道具的价格都没有，且只能鼠标中间后悔，不然就永远停留在了这个页面，让我不免怀疑是否在代码上连接到了真正的“给予”和“给予与装备”，或还是其他别的地方？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

<img width="1035" alt="屏幕截图 2024-07-18 004855" src="https://github.com/user-attachments/assets/b6920267-e760-4341-9e8e-9ba0036d909a">

**Comment by XyMinxin** [comment]
用最新版本新建存档也有同样问题吗？
