### ISSUE TITLE
标签工具无法读取MKV和MP4文件

### ISSUE THREAD

**Issue by dolen464** [XyMinxin/Brothel-King-Chinese-Translate#56]
### 在提问之前...

- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我正在使用最新版的汉化
- [X] 没有修改过游戏内的文件
- [ ] 没有使用旧版存档

### 描述你的问题

大佬你好，感谢你分享的标签工具，以前一直能正常使用，可以在里面读取MKV和MP4文件并便捷地改文件名，但最近不知道什么情况，以前可以读取的MKV和MP4文件都读取不了了，重新下载标签工具也还是读取不了，AVI就还能读取。请问怎么做才能让标签工具能正常读取MKV和MP4文件

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by XyMinxin** [comment]
这个我也不清楚喔，标签工具目前我没有对其做任何更改，理论上不应该存在之前能用现在不能用的情况。
你检查一下文件路径是否纯英文，试试能否解决，如果不行我也没办法。
```
    VIDEOFORMATS = (".webm", ".mpg", ".mkv", ".avi")
    IMGFORMATS = (".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp") + VIDEOFORMATS
```
工具内支持的文件只有这些，如果上面的不能解决，那尝试更换其他的格式。
