### ISSUE TITLE
遊戲會閃退

### ISSUE THREAD

**Issue by kkhfh3** [XyMinxin/Brothel-King-Chinese-Translate#89]
### 在提问之前...

- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的汉化
- [ ] 没有修改过游戏内的文件
- [ ] 没有使用旧版存档

### 描述你的问题

遊戲會閃退，我試兩種版本，一種是[二改+魔改+MOD整合包]，另一種是原版+漢化，但問題都一樣

### 如何复现

一、觀看新手教程選是
1. 對話到貧民窟劇情
2. 
![846](https://github.com/user-attachments/assets/b38d50ab-1775-43ef-bc3a-2daf49ecdf17)
3. 閃退

二、觀看新手教程選否或自由
1.開始遊戲
2.選完招牌業務
3.閃退(有時馬上閃退，有時操作)

### 截图

![847](https://github.com/user-attachments/assets/3e95fdd0-69a4-4cbe-8dc8-933236f9e7c2)
![849](https://github.com/user-attachments/assets/9e9bd3d6-881c-4667-954e-40a5a49547c3)
![850](https://github.com/user-attachments/assets/a5e57290-248c-4f28-9662-a93f3d3f88bb)
![854](https://github.com/user-attachments/assets/dff1135c-9cf9-4074-96a3-702d931ba7b7)
![855](https://github.com/user-attachments/assets/0e0bce27-9809-4def-9572-772941655dea)

### 还有别的吗？

[dialogue.txt](https://github.com/user-attachments/files/16638370/dialogue.txt)
[errors.txt](https://github.com/user-attachments/files/16638371/errors.txt)
[faq.txt](https://github.com/user-attachments/files/16638372/faq.txt)
[log.txt](https://github.com/user-attachments/files/16638373/log.txt)
[packstate_log.txt](https://github.com/user-attachments/files/16638374/packstate_log.txt)
[traceback.txt](https://github.com/user-attachments/files/16638375/traceback.txt)

**Comment by XyMinxin** [comment]
我无法复现这个bug，请尝试重新下载原版，重新覆盖汉化
1. 下载本体：[下载游戏本体](https://github.com/XyMinxin/Brothel-King-Chinese-Translate/releases/download/20240712/Brothel_King.v0.3t.zip)
2. 安装汉化：[下载汉化覆盖](https://github.com/XyMinxin/Brothel-King-Chinese-Translate/releases/download/20240811/Brothel_King-v0.3t-Chinese.zip)

**Comment by kkhfh3** [comment]
試了原版還是一樣，算了我放棄了，這遊戲大概與我無緣

**Comment by XyMinxin** [comment]
> 試了原版還是一樣，算了我放棄了，這遊戲大概與我無緣

建议详细说一下你的操作步骤。

比如解压原版压缩包后，你把汉化覆盖去哪个文件夹这样子，还有路径是否是英文。

尝试一下英文原版看看有没有问题，不要在这里下载，去作者论坛下载原版+原版补丁。

还有一个但我觉得应该没多大用的，用转区软件转简中环境看看。
